name: Deploy Trading Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Build Docker Image
        run: docker build -t mt4-bot .

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no mouradof@13.74.138.166 'docker stop trading_bot || true && docker rm trading_bot || true'
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no Dockerfile mouradof@13.74.138.166:/home/mouradof/
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no mouradof@13.74.138.166 'docker build -t mt4-bot . && docker run -d --name trading_bot mt4-bot'
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
